const TYPES = {
  // 系统相关
  SAVE_LOGIN_USER: 'SAVE_LOGIN_USER',
  LOAD_LOGIN_USER: 'LOAD_LOGIN_USER',
  LOGINOUT_USER: 'LOGINOUT_USER',
  ALERT_MESSAGE: 'ALERT_MESSAGE',
  OPEN_WIN_MODEL: 'OPEN_WIN_MODEL',
  OPEN_POPUP_MODEL: 'OPEN_POPUP_MODEL',
  NOTICE_MESSAGE: 'NOTICE_MESSAGE',
  GOTO_PAGE: 'GOTO_PAGE',
  CLOSE_PAGE: 'CLOSE_PAGE',
  UPDATE_LOADING_MODEL_VISIBLE: 'UPDATE_LOADING_MODEL_VISIBLE'
  // 某某模块
}

export default TYPES